phrase:
  project_id: 61b49556733b0ed52699587486214940
  push:
    sources:
    - file: ./source-locale/main/json-files/test.json
      params:
        file_format: simple_json
        locale_id: b79da9f28de785098c009249975a6a84
        update_translations: false
  pull:
    targets:
    - file: ./<locale_code>/test.json
      params:
        file_format: simple_json
